package common.message;

public enum MessageType {
    LOGIN, LOGIN_RESULT, LOGOUT, ONLINE_LIST_UPDATE,

    INVITE, INVITE_RECEIVED, INVITE_RESPONSE, INVITE_DECLINED, INVITE_FAILED,

    MATCH_START, MOVE_PAWN, PLACE_BARRICADE, MOVE_RESULT, TURN_TIMEOUT,
    SURRENDER, GAME_OVER,

    REMATCH_REQUEST, REMATCH_RESPONSE, REMATCH_TIMEOUT, MATCH_CLOSED,

    CHAT_MESSAGE,

    DISCONNECT_NOTICE, RECONNECTED,

    GET_HISTORY, HISTORY_RESULT, GET_RANKING, RANKING_RESULT,

    ERROR
}